apiVersion: app.k8s.io/v1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "component" "application" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "alluxio", "product_id": "alluxio-operator", "partner_name": "Alluxio"}'
spec:
  selector:
    matchLabels:
      {{- include "common.matchLabels" (dict "component" "application" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  componentKinds:
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: DaemonSet
  - group: ""
    kind: Service
  - group: ""
    kind: ConfigMap
  descriptor:
    type: "Alluxio"
    version: "0.1"
    description: "Alluxio Operator for Data Orchestration"
    maintainers:
    - name: Alluxio
      email: info@alluxio.com